#!/bin/bash

# .userenv/prompt | ver. 2.0 | 3.29.25

load_prompt() {
    local input=$1
    local c1=$2
    local c2=$3
    local c3=$4
    local c0=${nc}

    if [ -z $input ] || [ $input == "" ]; then
        local input=0
    fi

    if [ "$USER" == "root" ]; then
        local s0="#"
    else
        local s0="$"
    fi

    case $input in
        "1") PS1="\[$c1\]\u\[$c3\]:\[$c2\]\w\[$c3\]$s0\[$c0\] "; clear ;;
        "2") PS1="\[$c1\]\u\[$c3\]@\[$c1\]\h\n\[$c2\]\w\[$c3\]$s0\[$c0\] "; clear ;;
        "3") PS1="\[$c2\]\w\n\[$c1\]\u\[$c3\]$s0\[$c0\] "; clear ;;
        "4") PS1="\[$c1\]\u\n\[$c2\]\w\[$c3\]$s0\[$c0\] "; clear ;;
        "5") PS1="\[$c1\]\u\[$c3\]@\[$c1\]\h\[$c3\]:\[$c2\]\w\[$c3\]$s0\[$c0\] "; clear ;;
        "6") PS1="\[$c1\]\u\[$c3\]@\[$c1\]\h\[$c3\]:\[$c2\]\w\[$c3\]\n$s0\[$c0\] "; clear ;;
        "*") echo "Choose: \'(1)\' \'(2)\' \'(3)\' \'(4)\' \'(5)\'"
    esac
}

chk_color() {
    local f="$HOME/.userenv/color"
    if [ -z "${userenv_colors}" ];
    then
        [  -e "$f" ] && [ -f "$f" ] && source "$f" || PS1="\u@\h:\w${s} " && exit 0 &>/dev/null
    fi
}

setp() {
    chk_color

    input=$1
    c1=${2:-"cyan"}; c1=${!c1}
    c2=${3:-"bold_green"}; c2=${!c2}
    c3=${4:-"greener"}; c3=${!c3}

    load_prompt $input $c1 $c2 $c3
}

if [ -z "PS1" ] || [ "PS1" == "" ]; then
    PS1="\u@\h:\w "
fi

export PS1
